# Generated by Django 5.2 on 2025-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_answer_1_recoveryrequest_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='security_answer_1',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='security_answer_2',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='security_answer_3',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='security_answer_4',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='security_answer_5',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
