# Generated by Django 5.2 on 2025-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
