# Generated by Django 5.2 on 2025-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0010_mealtype_dailymenuitem_meal_type'),
        ('users', '0010_alter_guest_first_name_alter_guest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_meal_type',
            field=models.ManyToManyField(null=True, to='daily_menus.mealtype'),
        ),
    ]
