# Generated by Django 5.2 on 2025-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0010_mealtype_dailymenuitem_meal_type'),
        ('users', '0011_profile_allowed_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allowed_meal_type',
            field=models.ManyToManyField(blank=True, to='daily_menus.mealtype'),
        ),
    ]
