# Generated by Django 5.2 on 2025-05-08 13:08

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_status_is_cancel_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='is_cancel_status',
            new_name='is_visible',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 13, 8, 38, 250877, tzinfo=datetime.timezone.utc)),
        ),
    ]
