# Generated by Django 5.2 on 2025-05-08 13:10

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_is_cancel_status_status_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 13, 10, 33, 105769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
