# Generated by Django 5.2 on 2025-05-08 13:14

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_dailymenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 16, 44, 57, 984634)),
        ),
    ]
