# Generated by Django 5.2 on 2025-05-08 13:18

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_date_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 16, 48, 37, 180252)),
        ),
    ]
