# Generated by Django 5.2 on 2025-05-08 14:58

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_status_status_alter_reservation_date_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 18, 28, 12, 952805)),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('used', 'Used'), ('canceled', 'Canceled')], max_length=10, unique=True),
        ),
    ]
