# Generated by Django 5.2 on 2025-05-08 15:53

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_date_status_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 8, 19, 23, 22, 34151)),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('used', 'Used'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=10, unique=True),
        ),
    ]
