# Generated by Django 5.2 on 2025-05-15 13:48

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_reservation_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 15, 17, 18, 40, 560165)),
        ),
    ]
