# Generated by Django 5.2 on 2025-05-15 14:35

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_alter_reservation_date_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 5, 15, 18, 5, 19, 799018)),
        ),
    ]
