# Generated by Django 5.2 on 2025-06-05 23:01

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_alter_reservation_date_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 6, 5, 23, 1, 29, 157922)),
        ),
    ]
