# Generated by Django 5.2 on 2025-06-06 15:02

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_alter_reservation_date_status_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_status_updated',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 6, 6, 15, 2, 33, 579569)),
        ),
    ]
