# Generated by Django 5.2 on 2025-04-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Drinks',
        ),
        migrations.RenameModel(
            old_name='Food',
            new_name='Foods',
        ),
        migrations.RenameModel(
            old_name='SideDish',
            new_name='SideDishes',
        ),
    ]
