# Generated by Django 5.2 on 2025-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_rename_drinks_drink_rename_foods_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
