# Generated by Django 5.2 on 2025-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0004_alter_drink_description_alter_food_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='/static/images/Gheimeh.png', upload_to='food/'),
        ),
    ]
