# Generated by Django 5.2 on 2025-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0007_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/food/'),
        ),
    ]
