# Generated by Django 5.2 on 2025-04-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0001_initial'),
        ('menu_items', '0002_rename_drink_drinks_rename_food_foods_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMenuItems',
            new_name='DailyMenuItem',
        ),
    ]
