# Generated by Django 5.2 on 2025-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0002_rename_dailymenuitems_dailymenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenuitem',
            name='image',
            field=models.ImageField(default='/static/images/Gheimeh.png', upload_to='food/'),
        ),
    ]
