# Generated by Django 5.2 on 2025-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0004_alter_dailymenuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
    ]
