# Generated by Django 5.2 on 2025-04-30 15:10

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0005_alter_dailymenuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenuitem',
            name='normal_date',
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='expiration_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/food/'),
        ),
    ]
