# Generated by Django 5.2 on 2025-05-07 13:56

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0006_remove_dailymenuitem_normal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenuitem',
            name='reservation_deadline',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
