# Generated by Django 5.2 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0008_alter_dailymenuitem_reservation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
