# Generated by Django 5.2 on 2025-05-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0009_dailymenuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('launch', 'Launch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailymenuitem',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily_menus.mealtype'),
        ),
    ]
