# Generated by Django 5.2 on 2025-06-06 15:22

from django.db import migrations

def create_meal_types(apps, schema_editor):
    MealType = apps.get_model("daily_menus", "MealType")
    MEAL_TYPE_CHOICES = [
        ('breakfast', 'صبحانه'),
        ('launch', 'ناهار'),
        ('dinner', 'شام'),
        ('snack', 'میان وعده'),
    ]
    for meal_type, title in MEAL_TYPE_CHOICES:
        MealType.objects.get_or_create(
            meal_type=meal_type,
            defaults={"title": title}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('daily_menus', '0010_mealtype_dailymenuitem_meal_type'),
    ]

    operations = [
        migrations.RunPython(create_meal_types),
    ]
